use crate::core::diagnostics::*;
use crate::suites::macros::stub_log;
use crate::suites::world;
use after_effects_sys::*;
use rayon::prelude::*;
use std::os::raw::c_void;
use std::sync::RwLock;
use std::sync::atomic::{AtomicI32, Ordering};

// Global plugin path storage (UTF-16 for Windows)
static PLUGIN_PATH: RwLock<Option<Vec<u16>>> = RwLock::new(None);

/// Set plugin path for get_platform_data callback.
/// The path should be absolute and will be stored as UTF-16.
pub fn set_plugin_path(path: &std::path::Path) {
	let wide: Vec<u16> = {
		#[cfg(windows)]
		{
			use std::os::windows::ffi::OsStrExt;
			path.as_os_str()
				.encode_wide()
				.chain(std::iter::once(0))
				.collect()
		}
		#[cfg(not(windows))]
		{
			path.to_string_lossy()
				.encode_utf16()
				.chain(std::iter::once(0))
				.collect()
		}
	};
	if let Ok(mut guard) = PLUGIN_PATH.write() {
		*guard = Some(wide);
	}
}

// ============================================================================
// Stub Functions (Generated by macro)
// ============================================================================

stub_log!(begin_sampling_stub,
	_effect_ref: PF_ProgPtr,
	_qual: PF_Quality,
	_mf: PF_ModeFlags,
	_params: *mut PF_SampPB
);

stub_log!(subpixel_sample_stub,
	_effect_ref: PF_ProgPtr,
	_x: PF_Fixed,
	_y: PF_Fixed,
	_params: *const PF_SampPB,
	_dst_pixel: *mut PF_Pixel
);

stub_log!(area_sample_stub,
	_effect_ref: PF_ProgPtr,
	_x: PF_Fixed,
	_y: PF_Fixed,
	_params: *const PF_SampPB,
	_dst_pixel: *mut PF_Pixel
);

stub_log!(end_sampling_stub,
	_effect_ref: PF_ProgPtr,
	_qual: PF_Quality,
	_mf: PF_ModeFlags,
	_params: *mut PF_SampPB
);

stub_log!(composite_rect_stub,
	_effect_ref: PF_ProgPtr,
	_src_rect: *mut PF_Rect,
	_src_opacity: A_long,
	_source_wld: *mut PF_EffectWorld,
	_dest_x: A_long,
	_dest_y: A_long,
	_field_rdr: PF_Field,
	_xfer_mode: PF_XferMode,
	_dest_wld: *mut PF_EffectWorld
);

stub_log!(blend_stub,
	_effect_ref: PF_ProgPtr,
	_src1: *const PF_EffectWorld,
	_src2: *const PF_EffectWorld,
	_ratio: PF_Fixed,
	_dst: *mut PF_EffectWorld
);

stub_log!(convolve_stub,
	_effect_ref: PF_ProgPtr,
	_src: *mut PF_EffectWorld,
	_area: *const PF_Rect,
	_flags: PF_KernelFlags,
	_kernel_size: A_long,
	_a_kernel: *mut c_void,
	_r_kernel: *mut c_void,
	_g_kernel: *mut c_void,
	_b_kernel: *mut c_void,
	_dst: *mut PF_EffectWorld
);

stub_log!(copy_stub,
	_effect_ref: PF_ProgPtr,
	_src: *mut PF_EffectWorld,
	_dst: *mut PF_EffectWorld,
	_src_rect: *mut PF_Rect,
	_dst_rect: *mut PF_Rect
);

stub_log!(fill_stub,
	_effect_ref: PF_ProgPtr,
	_color: *const PF_Pixel,
	_dst_rect: *const PF_Rect,
	_world: *mut PF_EffectWorld
);

stub_log!(gaussian_kernel_stub,
	_effect_ref: PF_ProgPtr,
	_kRadius: A_FpLong,
	_flags: PF_KernelFlags,
	_multiplier: A_FpLong,
	_diameter: *mut A_long,
	_kernel: *mut c_void
);

unsafe extern "C" fn iterate_stub(
	in_data: *mut PF_InData,
	progress_base: A_long,
	progress_final: A_long,
	src: *mut PF_EffectWorld,
	area: *const PF_Rect,
	refcon: *mut c_void,
	pix_fn: ::std::option::Option<
		unsafe extern "C" fn(
			refcon: *mut c_void,
			x: A_long,
			y: A_long,
			in_: *mut PF_Pixel,
			out: *mut PF_Pixel,
		) -> PF_Err,
	>,
	dst: *mut PF_EffectWorld,
) -> PF_Err {
	#[cfg(not(feature = "diagnostics"))]
	let _ = (in_data, progress_base, progress_final);

	#[cfg(feature = "diagnostics")]
	DiagnosticBuilder::new()
		.set_name("UtilityCallbacks/iterate")
		.add_arg("in_data", format!("{:?}", in_data))
		.add_arg("progress_base", progress_base)
		.add_arg("progress_final", progress_final)
		.add_arg("src", format!("{:?}", src))
		.add_arg(
			"area",
			if !area.is_null() {
				format!("{:?}", area)
			} else {
				"(null)".to_string()
			},
		)
		.add_arg("refcon", format!("{:?}", refcon))
		.add_arg("pix_fn", if pix_fn.is_some() { "Some" } else { "None" })
		.add_arg("dst", format!("{:?}", dst))
		.set_result(0)
		.emit();

	if src.is_null() || dst.is_null() {
		return PF_Err_BAD_CALLBACK_PARAM as PF_Err;
	}

	let src_world = unsafe { &*src };
	let dst_world = unsafe { &*dst };

	if src_world.data.is_null() || dst_world.data.is_null() {
		return PF_Err_BAD_CALLBACK_PARAM as PF_Err;
	}

	let mut rect = if !area.is_null() {
		unsafe { *area }
	} else {
		PF_Rect {
			left: 0,
			top: 0,
			right: dst_world.width as i32,
			bottom: dst_world.height as i32,
		}
	};

	rect.left = rect.left.max(0);
	rect.top = rect.top.max(0);
	rect.right = rect.right.min(src_world.width as i32);
	rect.bottom = rect.bottom.min(src_world.height as i32);
	rect.right = rect.right.min(dst_world.width as i32);
	rect.bottom = rect.bottom.min(dst_world.height as i32);

	let start_x = rect.left as i32;
	let start_y = rect.top as i32;
	let end_x = rect.right as i32;
	let end_y = rect.bottom as i32;

	let width = (end_x - start_x).max(0);
	let height = (end_y - start_y).max(0);

	if width == 0 || height == 0 {
		return PF_Err_NONE as PF_Err;
	}

	let src_base_addr = src_world.data as usize;
	let src_rowbytes = src_world.rowbytes as isize;
	let dst_base_addr = dst_world.data as usize;
	let dst_rowbytes = dst_world.rowbytes as isize;
	let pixel_size = std::mem::size_of::<PF_Pixel>();

	debug_assert!(
		src_world.rowbytes >= (src_world.width as i32 * pixel_size as i32),
		"Source rowbytes smaller than width * pixel_size"
	);

	let refcon_addr = refcon as usize;
	let error_capsule = AtomicI32::new(PF_Err_NONE as i32);

	if let Some(func) = pix_fn {
		(0..height).into_par_iter().for_each(|y_offset| {
			if error_capsule.load(Ordering::Relaxed) != PF_Err_NONE as i32 {
				return;
			}

			let current_y = start_y + y_offset;
			let src_row_ptr =
				(src_base_addr as *const u8).wrapping_offset((current_y as isize) * src_rowbytes);
			let dst_row_ptr =
				(dst_base_addr as *mut u8).wrapping_offset((current_y as isize) * dst_rowbytes);
			let refcon_ptr = refcon_addr as *mut c_void;

			for x_offset in 0..width {
				let current_x = start_x + x_offset;
				let src_pixel =
					src_row_ptr.wrapping_add((current_x as usize) * pixel_size) as *mut PF_Pixel;
				let dst_pixel =
					dst_row_ptr.wrapping_add((current_x as usize) * pixel_size) as *mut PF_Pixel;

				let err = unsafe { func(refcon_ptr, current_x, current_y, src_pixel, dst_pixel) };
				if err != PF_Err_NONE as i32 {
					error_capsule.store(err, Ordering::Relaxed);
					return;
				}
			}
		});
	}

	error_capsule.load(Ordering::Relaxed) as PF_Err
}

stub_log!(premultiply_stub,
	_effect_ref: PF_ProgPtr,
	_forward: A_long,
	_dst: *mut PF_EffectWorld
);

stub_log!(premultiply_color_stub,
	_effect_ref: PF_ProgPtr,
	_src: *mut PF_EffectWorld,
	_color: *const PF_Pixel,
	_forward: A_long,
	_dst: *mut PF_EffectWorld
);

stub_log!(new_world_stub,
	_effect_ref: PF_ProgPtr,
	_width: A_long,
	_height: A_long,
	_flags: PF_NewWorldFlags,
	_world: *mut PF_EffectWorld
);

stub_log!(dispose_world_stub,
	_effect_ref: PF_ProgPtr,
	_world: *mut PF_EffectWorld
);

stub_log!(iterate_origin_stub,
	_in_data: *mut PF_InData,
	_progress_base: A_long,
	_progress_final: A_long,
	_src: *mut PF_EffectWorld,
	_area: *const PF_Rect,
	_origin: *const PF_Point,
	_refcon: *mut c_void,
	_pix_fn: ::std::option::Option<
		unsafe extern "C" fn(
			refcon: *mut c_void,
			x: A_long,
			y: A_long,
			in_: *mut PF_Pixel,
			out: *mut PF_Pixel,
		) -> PF_Err,
	>,
	_dst: *mut PF_EffectWorld
);

stub_log!(iterate_lut_stub,
	_in_data: *mut PF_InData,
	_progress_base: A_long,
	_progress_final: A_long,
	_src: *mut PF_EffectWorld,
	_area: *const PF_Rect,
	_a_lut0: *mut A_u_char,
	_r_lut0: *mut A_u_char,
	_g_lut0: *mut A_u_char,
	_b_lut0: *mut A_u_char,
	_dst: *mut PF_EffectWorld
);

stub_log!(transfer_rect_stub,
	_effect_ref: PF_ProgPtr,
	_quality: PF_Quality,
	_m_flags: PF_ModeFlags,
	_field: PF_Field,
	_src_rec: *const PF_Rect,
	_src_world: *const PF_EffectWorld,
	_comp_mode: *const PF_CompositeMode,
	_mask_world0: *const PF_MaskWorld,
	_dest_x: A_long,
	_dest_y: A_long,
	_dst_world: *mut PF_EffectWorld
);

stub_log!(transform_world_stub,
	_effect_ref: PF_ProgPtr,
	_quality: PF_Quality,
	_m_flags: PF_ModeFlags,
	_field: PF_Field,
	_src_world: *const PF_EffectWorld,
	_comp_mode: *const PF_CompositeMode,
	_mask_world0: *const PF_MaskWorld,
	_matrices: *const PF_FloatMatrix,
	_num_matrices: A_long,
	_src2dst_matrix: PF_Boolean,
	_dest_rect: *const PF_Rect,
	_dst_world: *mut PF_EffectWorld
);

stub_log!(get_callback_addr_stub,
	_effect_ref: PF_ProgPtr,
	_quality: PF_Quality,
	_mode_flags: PF_ModeFlags,
	_which_callback: PF_CallbackID,
	_fn_ptr: *mut PF_CallbackFunc
);

unsafe extern "C" fn app_stub(_effect_ref: PF_ProgPtr, _selector: A_long, ...) -> PF_Err {
	log::warn!("STUB: app called");
	PF_Err_NONE as PF_Err
}

stub_log!(iterate_origin_non_clip_src_stub,
	_in_data: *mut PF_InData,
	_progress_base: A_long,
	_progress_final: A_long,
	_src: *mut PF_EffectWorld,
	_area: *const PF_Rect,
	_origin: *const PF_Point,
	_refcon: *mut c_void,
	_pix_fn: ::std::option::Option<
		unsafe extern "C" fn(
			refcon: *mut c_void,
			x: A_long,
			y: A_long,
			in_: *mut PF_Pixel,
			out: *mut PF_Pixel,
		) -> PF_Err,
	>,
	_dst: *mut PF_EffectWorld
);

stub_log!(iterate_generic_stub,
	_iterationsL: A_long,
	_refconPV: *mut c_void,
	_fn_func: ::std::option::Option<
		unsafe extern "C" fn(
			refconPV: *mut c_void,
			thread_indexL: A_long,
			i: A_long,
			iterationsL: A_long,
		) -> PF_Err,
	>
);

stub_log!(subpixel_sample16_stub,
	_effect_ref: PF_ProgPtr,
	_x: PF_Fixed,
	_y: PF_Fixed,
	_params: *const PF_SampPB,
	_dst_pixel: *mut PF_Pixel16
);

stub_log!(area_sample16_stub,
	_effect_ref: PF_ProgPtr,
	_x: PF_Fixed,
	_y: PF_Fixed,
	_params: *const PF_SampPB,
	_dst_pixel: *mut PF_Pixel16
);

stub_log!(fill16_stub,
	_effect_ref: PF_ProgPtr,
	_color: *const PF_Pixel16,
	_dst_rect: *const PF_Rect,
	_world: *mut PF_EffectWorld
);

stub_log!(premultiply_color16_stub,
	_effect_ref: PF_ProgPtr,
	_src: *mut PF_EffectWorld,
	_color: *const PF_Pixel16,
	_forward: A_long,
	_dst: *mut PF_EffectWorld
);

stub_log!(iterate16_stub,
	_in_data: *mut PF_InData,
	_progress_base: A_long,
	_progress_final: A_long,
	_src: *mut PF_EffectWorld,
	_area: *const PF_Rect,
	_refcon: *mut c_void,
	_pix_fn: ::std::option::Option<
		unsafe extern "C" fn(
			refcon: *mut c_void,
			x: A_long,
			y: A_long,
			in_: *mut PF_Pixel16,
			out: *mut PF_Pixel16,
		) -> PF_Err,
	>,
	_dst: *mut PF_EffectWorld
);

stub_log!(iterate_origin16_stub,
	_in_data: *mut PF_InData,
	_progress_base: A_long,
	_progress_final: A_long,
	_src: *mut PF_EffectWorld,
	_area: *const PF_Rect,
	_origin: *const PF_Point,
	_refcon: *mut c_void,
	_pix_fn: ::std::option::Option<
		unsafe extern "C" fn(
			refcon: *mut c_void,
			x: A_long,
			y: A_long,
			in_: *mut PF_Pixel16,
			out: *mut PF_Pixel16,
		) -> PF_Err,
	>,
	_dst: *mut PF_EffectWorld
);

stub_log!(iterate_origin_non_clip_src16_stub,
	_in_data: *mut PF_InData,
	_progress_base: A_long,
	_progress_final: A_long,
	_src: *mut PF_EffectWorld,
	_area: *const PF_Rect,
	_origin: *const PF_Point,
	_refcon: *mut c_void,
	_pix_fn: ::std::option::Option<
		unsafe extern "C" fn(
			refcon: *mut c_void,
			x: A_long,
			y: A_long,
			in_: *mut PF_Pixel16,
			out: *mut PF_Pixel16,
		) -> PF_Err,
	>,
	_dst: *mut PF_EffectWorld
);

/// # Safety
///
/// This function is unsafe because it handles raw pointers and performs unchecked operations.
pub unsafe extern "C" fn get_pixel_data8_sys(
	worldP: *mut PF_EffectWorld,
	pixelsP0: PF_PixelPtr,
	pixPP: *mut *mut PF_Pixel8,
) -> PF_Err {
	DiagnosticBuilder::new()
		.set_name("Utility/get_pixel_data8")
		.add_arg("worldP", format!("{:x}", worldP as usize))
		.add_arg("pixelsP0", format!("{:x}", pixelsP0 as usize))
		.add_arg("pixPP", format!("{:?}", pixPP))
		.emit();

	if !pixPP.is_null() && !worldP.is_null() {
		// SAFETY: The caller guarantees valid pointers.
		unsafe {
			*pixPP = (*worldP).data as *mut PF_Pixel8;
		}
	}

	PF_Err_NONE as PF_Err
}

stub_log!(get_pixel_data16_stub,
	_worldP: *mut PF_EffectWorld,
	_pixelsP0: PF_PixelPtr,
	_pixPP: *mut *mut PF_Pixel16
);

// ============================================================================
// Implemented Functions
// ============================================================================

/// PF_PlatDataID constants
const PF_PLAT_DATA_EXE_FILE_PATH_W: PF_PlatDataID = 7;
const PF_PLAT_DATA_RES_FILE_PATH_W: PF_PlatDataID = 8;

unsafe extern "C" fn get_platform_data_impl(
	_effect_ref: PF_ProgPtr,
	which: PF_PlatDataID,
	data: *mut c_void,
) -> PF_Err {
	#[cfg(feature = "diagnostics")]
	DiagnosticBuilder::new()
		.set_name("get_platform_data")
		.add_arg("which", &which)
		.add_arg("data", format!("{:?}", data))
		.emit();

	if data.is_null() {
		log::warn!("get_platform_data: data pointer is null");
		return PF_Err_BAD_CALLBACK_PARAM as PF_Err;
	}

	match which {
		PF_PLAT_DATA_EXE_FILE_PATH_W | PF_PLAT_DATA_RES_FILE_PATH_W => {
			// Return plugin path as UTF-16
			if let Ok(guard) = PLUGIN_PATH.read() {
				if let Some(ref path) = *guard {
					// Copy path to output buffer (max AEFX_MAX_PATH = 260)
					let dst = data as *mut u16;
					const AEFX_MAX_PATH: usize = 260;
					let copy_len = path.len().min(AEFX_MAX_PATH);
					unsafe {
						std::ptr::copy_nonoverlapping(path.as_ptr(), dst, copy_len);
						// Ensure null termination if truncated
						if path.len() > AEFX_MAX_PATH {
							*dst.add(AEFX_MAX_PATH - 1) = 0;
						}
					}
					log::info!("get_platform_data: returned plugin path (len={})", copy_len);
					return PF_Err_NONE as PF_Err;
				}
			}
			log::warn!("get_platform_data: plugin path not set");
			PF_Err_BAD_CALLBACK_PARAM as PF_Err
		}
		_ => {
			log::warn!("get_platform_data: unsupported which={}", which);
			PF_Err_NONE as PF_Err // Return OK for unsupported, as AE does
		}
	}
}

// ============================================================================
// Factory Function
// ============================================================================

/// Creates a `_PF_UtilCallbacks` instance with all callbacks populated.
pub fn create_utility_callbacks() -> Box<_PF_UtilCallbacks> {
	Box::new(_PF_UtilCallbacks {
		begin_sampling: Some(begin_sampling_stub),
		subpixel_sample: Some(subpixel_sample_stub),
		area_sample: Some(area_sample_stub),
		get_batch_func_is_deprecated: std::ptr::null_mut(),
		end_sampling: Some(end_sampling_stub),
		composite_rect: Some(composite_rect_stub),
		blend: Some(blend_stub),
		convolve: Some(convolve_stub),
		copy: Some(copy_stub),
		fill: Some(fill_stub),
		gaussian_kernel: Some(gaussian_kernel_stub),
		iterate: Some(iterate_stub),
		premultiply: Some(premultiply_stub),
		premultiply_color: Some(premultiply_color_stub),
		new_world: Some(new_world_stub),
		dispose_world: Some(dispose_world_stub),
		iterate_origin: Some(iterate_origin_stub),
		iterate_lut: Some(iterate_lut_stub),
		transfer_rect: Some(transfer_rect_stub),
		transform_world: Some(transform_world_stub),
		host_new_handle: Some(crate::suites::handle::host_new_handle_impl),
		host_lock_handle: Some(crate::suites::handle::host_lock_handle_impl),
		host_unlock_handle: Some(crate::suites::handle::host_unlock_handle_impl),
		host_dispose_handle: Some(crate::suites::handle::host_dispose_handle_impl),
		get_callback_addr: Some(get_callback_addr_stub),
		app: Some(app_stub),
		ansi: crate::suites::SUITE_CONTAINER.ansi, // Use existing ANSI callbacks
		colorCB: PF_ColorCallbacks {
			RGBtoHLS: None,
			HLStoRGB: None,
			RGBtoYIQ: None,
			YIQtoRGB: None,
			Luminance: None,
			Hue: None,
			Lightness: None,
			Saturation: None,
		},
		get_platform_data: Some(get_platform_data_impl),
		host_get_handle_size: Some(crate::suites::handle::host_get_handle_size_impl),
		iterate_origin_non_clip_src: Some(iterate_origin_non_clip_src_stub),
		iterate_generic: Some(iterate_generic_stub),
		host_resize_handle: Some(crate::suites::handle::host_resize_handle_impl),
		subpixel_sample16: Some(subpixel_sample16_stub),
		area_sample16: Some(area_sample16_stub),
		fill16: Some(fill16_stub),
		premultiply_color16: Some(premultiply_color16_stub),
		iterate16: Some(iterate16_stub),
		iterate_origin16: Some(iterate_origin16_stub),
		iterate_origin_non_clip_src16: Some(iterate_origin_non_clip_src16_stub),
		get_pixel_data8: Some(get_pixel_data8_sys),
		get_pixel_data16: Some(get_pixel_data16_stub),
		reserved: [0; 1],
	})
}
