use crate::core::diagnostics::*;
use crate::suites::macros::stub_log;
use after_effects_sys::*;
use rayon::prelude::*;
use std::os::raw::c_void;
use std::sync::atomic::{AtomicI32, Ordering};

/// Encode a path as a null-terminated UTF-16 string, the representation
/// `get_platform_data` hands back for `PF_PlatData_*_FILE_PATH_W` queries.
fn encode_path_utf16(path: &std::path::Path) -> Vec<u16> {
	#[cfg(windows)]
	{
		use std::os::windows::ffi::OsStrExt;
		path.as_os_str().encode_wide().chain(std::iter::once(0)).collect()
	}
	#[cfg(not(windows))]
	{
		path.to_string_lossy()
			.encode_utf16()
			.chain(std::iter::once(0))
			.collect()
	}
}

// ============================================================================
// Stub Functions (Generated by macro)
// ============================================================================

stub_log!(begin_sampling_stub,
	_effect_ref: PF_ProgPtr,
	_qual: PF_Quality,
	_mf: PF_ModeFlags,
	_params: *mut PF_SampPB
);

stub_log!(subpixel_sample_stub,
	_effect_ref: PF_ProgPtr,
	_x: PF_Fixed,
	_y: PF_Fixed,
	_params: *const PF_SampPB,
	_dst_pixel: *mut PF_Pixel
);

stub_log!(area_sample_stub,
	_effect_ref: PF_ProgPtr,
	_x: PF_Fixed,
	_y: PF_Fixed,
	_params: *const PF_SampPB,
	_dst_pixel: *mut PF_Pixel
);

stub_log!(end_sampling_stub,
	_effect_ref: PF_ProgPtr,
	_qual: PF_Quality,
	_mf: PF_ModeFlags,
	_params: *mut PF_SampPB
);

stub_log!(composite_rect_stub,
	_effect_ref: PF_ProgPtr,
	_src_rect: *mut PF_Rect,
	_src_opacity: A_long,
	_source_wld: *mut PF_EffectWorld,
	_dest_x: A_long,
	_dest_y: A_long,
	_field_rdr: PF_Field,
	_xfer_mode: PF_XferMode,
	_dest_wld: *mut PF_EffectWorld
);

stub_log!(blend_stub,
	_effect_ref: PF_ProgPtr,
	_src1: *const PF_EffectWorld,
	_src2: *const PF_EffectWorld,
	_ratio: PF_Fixed,
	_dst: *mut PF_EffectWorld
);

stub_log!(convolve_stub,
	_effect_ref: PF_ProgPtr,
	_src: *mut PF_EffectWorld,
	_area: *const PF_Rect,
	_flags: PF_KernelFlags,
	_kernel_size: A_long,
	_a_kernel: *mut c_void,
	_r_kernel: *mut c_void,
	_g_kernel: *mut c_void,
	_b_kernel: *mut c_void,
	_dst: *mut PF_EffectWorld
);

unsafe extern "C" fn copy_sys(
	_effect_ref: PF_ProgPtr,
	src: *mut PF_EffectWorld,
	dst: *mut PF_EffectWorld,
	_src_rect: *mut PF_Rect,
	_dst_rect: *mut PF_Rect,
) -> PF_Err {
	//== Validation ==//
	if src.is_null() {
		log::warn!("copy: src pointer is null");
		return PF_Err_BAD_CALLBACK_PARAM as PF_Err;
	}

	if dst.is_null() {
		log::warn!("copy: dst pointer is null");
		return PF_Err_BAD_CALLBACK_PARAM as PF_Err;
	}

	//== Implementation ==//
	// Copy src into dst row by row: the worlds may have different strides, and
	// each row only owns `rowbytes` bytes, so copying more (or advancing by
	// anything but the stride) reads/writes out of bounds.
	let src_ref = &unsafe { *src };
	let dst_ref = &mut unsafe { *dst };

	if !src_ref.data.is_null() && !dst_ref.data.is_null() {
		let rows = src_ref.height.min(dst_ref.height).max(0) as usize;
		let src_stride = src_ref.rowbytes.max(0) as usize;
		let dst_stride = dst_ref.rowbytes.max(0) as usize;
		let bytes_per_row = src_stride.min(dst_stride);

		for row in 0..rows {
			let src_ptr = unsafe { (src_ref.data as *const u8).add(row * src_stride) };
			let dst_ptr = unsafe { (dst_ref.data as *mut u8).add(row * dst_stride) };

			unsafe { std::ptr::copy_nonoverlapping(src_ptr, dst_ptr, bytes_per_row) };
		}
	}

	diag!("UtilityCallbacks/copy",
		"effect_ref" => _effect_ref as usize,
		"src" => format!("{:?}", src),
		"dst" => format!("{:?}", dst),
		"src_rect" => format!("{:?}", _src_rect),
		"dst_rect" => format!("{:?}", _dst_rect),
	);

	PF_Err_NONE as PF_Err
}

stub_log!(fill_stub,
	_effect_ref: PF_ProgPtr,
	_color: *const PF_Pixel,
	_dst_rect: *const PF_Rect,
	_world: *mut PF_EffectWorld
);

stub_log!(gaussian_kernel_stub,
	_effect_ref: PF_ProgPtr,
	_kRadius: A_FpLong,
	_flags: PF_KernelFlags,
	_multiplier: A_FpLong,
	_diameter: *mut A_long,
	_kernel: *mut c_void
);

// `PF_Err_NONE` is `u32` on macOS and `i32` elsewhere, so `as i32` is redundant
// here (Windows/Linux) but required on macOS. Silence the platform-specific lint.
#[allow(clippy::unnecessary_cast)]
unsafe extern "C" fn iterate_stub(
	in_data: *mut PF_InData,
	progress_base: A_long,
	progress_final: A_long,
	src: *mut PF_EffectWorld,
	area: *const PF_Rect,
	refcon: *mut c_void,
	pix_fn: ::std::option::Option<
		unsafe extern "C" fn(
			refcon: *mut c_void,
			x: A_long,
			y: A_long,
			in_: *mut PF_Pixel,
			out: *mut PF_Pixel,
		) -> PF_Err,
	>,
	dst: *mut PF_EffectWorld,
) -> PF_Err {
	#[cfg(not(feature = "diagnostics"))]
	let _ = (in_data, progress_base, progress_final);

	#[cfg(feature = "diagnostics")]
	DiagnosticBuilder::new()
		.set_name("UtilityCallbacks/iterate")
		.add_arg("in_data", format!("{:?}", in_data))
		.add_arg("progress_base", progress_base)
		.add_arg("progress_final", progress_final)
		.add_arg("src", format!("{:?}", src))
		.add_arg(
			"area",
			if !area.is_null() {
				format!("{:?}", area)
			} else {
				"(null)".to_string()
			},
		)
		.add_arg("refcon", format!("{:?}", refcon))
		.add_arg("pix_fn", if pix_fn.is_some() { "Some" } else { "None" })
		.add_arg("dst", format!("{:?}", dst))
		.emit();

	if dst.is_null() {
		return PF_Err_BAD_CALLBACK_PARAM as PF_Err;
	}

	// A null `src` is legal: the SDK's `iterate` then walks `dst` only, which is
	// how generator effects (no input layer) invoke it. Fall back to `dst` as the
	// source so the bounds and the per-pixel `in`/`out` pointers coincide, matching
	// AE's dst-only iteration -- rather than rejecting it as a bad parameter.
	let src = if src.is_null() { dst } else { src };

	let src_world = unsafe { &*src };
	let dst_world = unsafe { &*dst };

	if src_world.data.is_null() || dst_world.data.is_null() {
		return PF_Err_BAD_CALLBACK_PARAM as PF_Err;
	}

	let mut rect = if !area.is_null() {
		unsafe { *area }
	} else {
		PF_Rect {
			left: 0,
			top: 0,
			right: dst_world.width,
			bottom: dst_world.height,
		}
	};

	rect.left = rect.left.max(0);
	rect.top = rect.top.max(0);
	rect.right = rect.right.min(src_world.width);
	rect.bottom = rect.bottom.min(src_world.height);
	rect.right = rect.right.min(dst_world.width);
	rect.bottom = rect.bottom.min(dst_world.height);

	let start_x = rect.left;
	let start_y = rect.top;
	let end_x = rect.right;
	let end_y = rect.bottom;

	let width = (end_x - start_x).max(0);
	let height = (end_y - start_y).max(0);

	if width == 0 || height == 0 {
		return PF_Err_NONE as PF_Err;
	}

	let src_base_addr = src_world.data as usize;
	let src_rowbytes = src_world.rowbytes as isize;
	let dst_base_addr = dst_world.data as usize;
	let dst_rowbytes = dst_world.rowbytes as isize;
	let pixel_size = std::mem::size_of::<PF_Pixel>();

	debug_assert!(
		src_world.rowbytes >= (src_world.width * pixel_size as i32),
		"Source rowbytes smaller than width * pixel_size"
	);

	let refcon_addr = refcon as usize;
	let error_capsule = AtomicI32::new(PF_Err_NONE as i32);

	if let Some(func) = pix_fn {
		(0..height).into_par_iter().for_each(|y_offset| {
			if error_capsule.load(Ordering::Relaxed) != PF_Err_NONE as i32 {
				return;
			}

			let current_y = start_y + y_offset;
			let src_row_ptr = (src_base_addr as *const u8).wrapping_offset((current_y as isize) * src_rowbytes);
			let dst_row_ptr = (dst_base_addr as *mut u8).wrapping_offset((current_y as isize) * dst_rowbytes);
			let refcon_ptr = refcon_addr as *mut c_void;

			for x_offset in 0..width {
				let current_x = start_x + x_offset;
				let src_pixel = src_row_ptr.wrapping_add((current_x as usize) * pixel_size) as *mut PF_Pixel;
				let dst_pixel = dst_row_ptr.wrapping_add((current_x as usize) * pixel_size) as *mut PF_Pixel;

				let err = unsafe { func(refcon_ptr, current_x, current_y, src_pixel, dst_pixel) };
				if err != PF_Err_NONE as i32 {
					error_capsule.store(err, Ordering::Relaxed);
					return;
				}
			}
		});
	}

	error_capsule.load(Ordering::Relaxed) as PF_Err
}

stub_log!(premultiply_stub,
	_effect_ref: PF_ProgPtr,
	_forward: A_long,
	_dst: *mut PF_EffectWorld
);

stub_log!(premultiply_color_stub,
	_effect_ref: PF_ProgPtr,
	_src: *mut PF_EffectWorld,
	_color: *const PF_Pixel,
	_forward: A_long,
	_dst: *mut PF_EffectWorld
);

stub_log!(new_world_stub,
	_effect_ref: PF_ProgPtr,
	_width: A_long,
	_height: A_long,
	_flags: PF_NewWorldFlags,
	_world: *mut PF_EffectWorld
);

stub_log!(dispose_world_stub,
	_effect_ref: PF_ProgPtr,
	_world: *mut PF_EffectWorld
);

stub_log!(iterate_origin_stub,
	_in_data: *mut PF_InData,
	_progress_base: A_long,
	_progress_final: A_long,
	_src: *mut PF_EffectWorld,
	_area: *const PF_Rect,
	_origin: *const PF_Point,
	_refcon: *mut c_void,
	_pix_fn: ::std::option::Option<
		unsafe extern "C" fn(
			refcon: *mut c_void,
			x: A_long,
			y: A_long,
			in_: *mut PF_Pixel,
			out: *mut PF_Pixel,
		) -> PF_Err,
	>,
	_dst: *mut PF_EffectWorld
);

stub_log!(iterate_lut_stub,
	_in_data: *mut PF_InData,
	_progress_base: A_long,
	_progress_final: A_long,
	_src: *mut PF_EffectWorld,
	_area: *const PF_Rect,
	_a_lut0: *mut A_u_char,
	_r_lut0: *mut A_u_char,
	_g_lut0: *mut A_u_char,
	_b_lut0: *mut A_u_char,
	_dst: *mut PF_EffectWorld
);

stub_log!(transfer_rect_stub,
	_effect_ref: PF_ProgPtr,
	_quality: PF_Quality,
	_m_flags: PF_ModeFlags,
	_field: PF_Field,
	_src_rec: *const PF_Rect,
	_src_world: *const PF_EffectWorld,
	_comp_mode: *const PF_CompositeMode,
	_mask_world0: *const PF_MaskWorld,
	_dest_x: A_long,
	_dest_y: A_long,
	_dst_world: *mut PF_EffectWorld
);

stub_log!(transform_world_stub,
	_effect_ref: PF_ProgPtr,
	_quality: PF_Quality,
	_m_flags: PF_ModeFlags,
	_field: PF_Field,
	_src_world: *const PF_EffectWorld,
	_comp_mode: *const PF_CompositeMode,
	_mask_world0: *const PF_MaskWorld,
	_matrices: *const PF_FloatMatrix,
	_num_matrices: A_long,
	_src2dst_matrix: PF_Boolean,
	_dest_rect: *const PF_Rect,
	_dst_world: *mut PF_EffectWorld
);

stub_log!(get_callback_addr_stub,
	_effect_ref: PF_ProgPtr,
	_quality: PF_Quality,
	_mode_flags: PF_ModeFlags,
	_which_callback: PF_CallbackID,
	_fn_ptr: *mut PF_CallbackFunc
);

unsafe extern "C" fn app_stub(_effect_ref: PF_ProgPtr, _selector: A_long, _args: ...) -> PF_Err {
	log::warn!("STUB: app called");
	PF_Err_NONE as PF_Err
}

stub_log!(iterate_origin_non_clip_src_stub,
	_in_data: *mut PF_InData,
	_progress_base: A_long,
	_progress_final: A_long,
	_src: *mut PF_EffectWorld,
	_area: *const PF_Rect,
	_origin: *const PF_Point,
	_refcon: *mut c_void,
	_pix_fn: ::std::option::Option<
		unsafe extern "C" fn(
			refcon: *mut c_void,
			x: A_long,
			y: A_long,
			in_: *mut PF_Pixel,
			out: *mut PF_Pixel,
		) -> PF_Err,
	>,
	_dst: *mut PF_EffectWorld
);

stub_log!(iterate_generic_stub,
	_iterationsL: A_long,
	_refconPV: *mut c_void,
	_fn_func: ::std::option::Option<
		unsafe extern "C" fn(
			refconPV: *mut c_void,
			thread_indexL: A_long,
			i: A_long,
			iterationsL: A_long,
		) -> PF_Err,
	>
);

stub_log!(subpixel_sample16_stub,
	_effect_ref: PF_ProgPtr,
	_x: PF_Fixed,
	_y: PF_Fixed,
	_params: *const PF_SampPB,
	_dst_pixel: *mut PF_Pixel16
);

stub_log!(area_sample16_stub,
	_effect_ref: PF_ProgPtr,
	_x: PF_Fixed,
	_y: PF_Fixed,
	_params: *const PF_SampPB,
	_dst_pixel: *mut PF_Pixel16
);

stub_log!(fill16_stub,
	_effect_ref: PF_ProgPtr,
	_color: *const PF_Pixel16,
	_dst_rect: *const PF_Rect,
	_world: *mut PF_EffectWorld
);

stub_log!(premultiply_color16_stub,
	_effect_ref: PF_ProgPtr,
	_src: *mut PF_EffectWorld,
	_color: *const PF_Pixel16,
	_forward: A_long,
	_dst: *mut PF_EffectWorld
);

stub_log!(iterate16_stub,
	_in_data: *mut PF_InData,
	_progress_base: A_long,
	_progress_final: A_long,
	_src: *mut PF_EffectWorld,
	_area: *const PF_Rect,
	_refcon: *mut c_void,
	_pix_fn: ::std::option::Option<
		unsafe extern "C" fn(
			refcon: *mut c_void,
			x: A_long,
			y: A_long,
			in_: *mut PF_Pixel16,
			out: *mut PF_Pixel16,
		) -> PF_Err,
	>,
	_dst: *mut PF_EffectWorld
);

stub_log!(iterate_origin16_stub,
	_in_data: *mut PF_InData,
	_progress_base: A_long,
	_progress_final: A_long,
	_src: *mut PF_EffectWorld,
	_area: *const PF_Rect,
	_origin: *const PF_Point,
	_refcon: *mut c_void,
	_pix_fn: ::std::option::Option<
		unsafe extern "C" fn(
			refcon: *mut c_void,
			x: A_long,
			y: A_long,
			in_: *mut PF_Pixel16,
			out: *mut PF_Pixel16,
		) -> PF_Err,
	>,
	_dst: *mut PF_EffectWorld
);

stub_log!(iterate_origin_non_clip_src16_stub,
	_in_data: *mut PF_InData,
	_progress_base: A_long,
	_progress_final: A_long,
	_src: *mut PF_EffectWorld,
	_area: *const PF_Rect,
	_origin: *const PF_Point,
	_refcon: *mut c_void,
	_pix_fn: ::std::option::Option<
		unsafe extern "C" fn(
			refcon: *mut c_void,
			x: A_long,
			y: A_long,
			in_: *mut PF_Pixel16,
			out: *mut PF_Pixel16,
		) -> PF_Err,
	>,
	_dst: *mut PF_EffectWorld
);

/// # Safety
///
/// This function is unsafe because it handles raw pointers and performs unchecked operations.
pub unsafe extern "C" fn get_pixel_data8_sys(
	worldP: *mut PF_EffectWorld,
	_pixelsP0: PF_PixelPtr,
	pixPP: *mut *mut PF_Pixel8,
) -> PF_Err {
	diag!("Utility/get_pixel_data8",
		"worldP" => format!("{:x}", worldP as usize),
		"pixelsP0" => format!("{:x}", _pixelsP0 as usize),
		"pixPP" => format!("{:?}", pixPP),
	);

	if !pixPP.is_null() && !worldP.is_null() {
		// SAFETY: The caller guarantees valid pointers.
		unsafe {
			*pixPP = (*worldP).data as *mut PF_Pixel8;
		}
	}

	PF_Err_NONE as PF_Err
}

stub_log!(get_pixel_data16_stub,
	_worldP: *mut PF_EffectWorld,
	_pixelsP0: PF_PixelPtr,
	_pixPP: *mut *mut PF_Pixel16
);

// ============================================================================
// Implemented Functions
// ============================================================================

/// PF_PlatDataID constants
const PF_PLAT_DATA_EXE_FILE_PATH_W: PF_PlatDataID = 7;
const PF_PLAT_DATA_RES_FILE_PATH_W: PF_PlatDataID = 8;

unsafe extern "C" fn get_platform_data_impl(effect_ref: PF_ProgPtr, which: PF_PlatDataID, data: *mut c_void) -> PF_Err {
	#[cfg(feature = "diagnostics")]
	DiagnosticBuilder::new()
		.set_name("get_platform_data")
		.add_arg("which", which)
		.add_arg("data", format!("{:?}", data))
		.emit();

	if data.is_null() {
		log::warn!("get_platform_data: data pointer is null");
		return PF_Err_BAD_CALLBACK_PARAM as PF_Err;
	}

	match which {
		PF_PLAT_DATA_EXE_FILE_PATH_W | PF_PLAT_DATA_RES_FILE_PATH_W => {
			// The path is per instance (recovered via effect_ref), so loading a
			// second plugin can't clobber the first one's answer.
			let Some(instance) = crate::PluginInstance::get_instance_ptr(effect_ref) else {
				log::warn!("get_platform_data: no instance for effect_ref");
				return PF_Err_BAD_CALLBACK_PARAM as PF_Err;
			};
			let Some(path) = unsafe { instance.as_ref() }.resolved_binary_path() else {
				log::warn!("get_platform_data: plugin path not set (in-process entry point?)");
				return PF_Err_BAD_CALLBACK_PARAM as PF_Err;
			};

			// Copy the UTF-16 path into the output buffer (max AEFX_MAX_PATH = 260)
			let wide = encode_path_utf16(path);
			let dst = data as *mut u16;
			const AEFX_MAX_PATH: usize = 260;
			let copy_len = wide.len().min(AEFX_MAX_PATH);
			unsafe {
				std::ptr::copy_nonoverlapping(wide.as_ptr(), dst, copy_len);
				// Ensure null termination if truncated
				if wide.len() > AEFX_MAX_PATH {
					*dst.add(AEFX_MAX_PATH - 1) = 0;
				}
			}
			log::debug!("get_platform_data: returned plugin path (len={})", copy_len);
			PF_Err_NONE as PF_Err
		}
		_ => {
			log::warn!("get_platform_data: unsupported which={}", which);
			PF_Err_NONE as PF_Err // Return OK for unsupported, as AE does
		}
	}
}

// ============================================================================
// Factory Function
// ============================================================================

/// Creates a `_PF_UtilCallbacks` instance with all callbacks populated.
pub fn create_utility_callbacks() -> Box<_PF_UtilCallbacks> {
	Box::new(_PF_UtilCallbacks {
		begin_sampling: Some(begin_sampling_stub),
		subpixel_sample: Some(subpixel_sample_stub),
		area_sample: Some(area_sample_stub),
		get_batch_func_is_deprecated: std::ptr::null_mut(),
		end_sampling: Some(end_sampling_stub),
		composite_rect: Some(composite_rect_stub),
		blend: Some(blend_stub),
		convolve: Some(convolve_stub),
		copy: Some(copy_sys),
		fill: Some(fill_stub),
		gaussian_kernel: Some(gaussian_kernel_stub),
		iterate: Some(iterate_stub),
		premultiply: Some(premultiply_stub),
		premultiply_color: Some(premultiply_color_stub),
		new_world: Some(new_world_stub),
		dispose_world: Some(dispose_world_stub),
		iterate_origin: Some(iterate_origin_stub),
		iterate_lut: Some(iterate_lut_stub),
		transfer_rect: Some(transfer_rect_stub),
		transform_world: Some(transform_world_stub),
		host_new_handle: Some(crate::suites::handle::host_new_handle_impl),
		host_lock_handle: Some(crate::suites::handle::host_lock_handle_impl),
		host_unlock_handle: Some(crate::suites::handle::host_unlock_handle_impl),
		host_dispose_handle: Some(crate::suites::handle::host_dispose_handle_impl),
		get_callback_addr: Some(get_callback_addr_stub),
		app: Some(app_stub),
		ansi: crate::suites::SUITE_CONTAINER.ansi, // Use existing ANSI callbacks
		colorCB: PF_ColorCallbacks {
			RGBtoHLS: None,
			HLStoRGB: None,
			RGBtoYIQ: None,
			YIQtoRGB: None,
			Luminance: None,
			Hue: None,
			Lightness: None,
			Saturation: None,
		},
		get_platform_data: Some(get_platform_data_impl),
		host_get_handle_size: Some(crate::suites::handle::host_get_handle_size_impl),
		iterate_origin_non_clip_src: Some(iterate_origin_non_clip_src_stub),
		iterate_generic: Some(iterate_generic_stub),
		host_resize_handle: Some(crate::suites::handle::host_resize_handle_impl),
		subpixel_sample16: Some(subpixel_sample16_stub),
		area_sample16: Some(area_sample16_stub),
		fill16: Some(fill16_stub),
		premultiply_color16: Some(premultiply_color16_stub),
		iterate16: Some(iterate16_stub),
		iterate_origin16: Some(iterate_origin16_stub),
		iterate_origin_non_clip_src16: Some(iterate_origin_non_clip_src16_stub),
		get_pixel_data8: Some(get_pixel_data8_sys),
		get_pixel_data16: Some(get_pixel_data16_stub),
		reserved: [0; 1],
	})
}

#[cfg(test)]
mod tests {
	use wrapper::{Depth8, Layer};

	use super::*;

	#[test]
	fn test_copy() {
		//== Create dummy worlds ==//
		let mut src_layer = Layer::<Depth8>::black(4, 4);
		let mut dst_layer = Layer::<Depth8>::blank(4, 4);

		let mut src_world = src_layer.as_sys();
		let mut dst_world = dst_layer.as_sys();

		//== Call ==//
		let result = unsafe {
			copy_sys(
				std::ptr::null_mut(),
				&mut src_world,
				&mut dst_world,
				std::ptr::null_mut(),
				std::ptr::null_mut(),
			)
		};

		assert_eq!(result, PF_Err_NONE as PF_Err);

		// Verify that the destination world now contains the copied pixels
		for x in 0..64 {
			let src_pixel = unsafe { *(src_world.data as *const i8).add(x) };
			let dst_pixel = unsafe { *(dst_world.data as *const i8).add(x) };
			assert_eq!(src_pixel, dst_pixel, "Pixel mismatch at index {}", x);
		}
	}
}
